---
kind: pipeline
type: kubernetes
name: Continuous Integration

platform:
  os: linux
  arch: amd64

steps:
- name: Setup environment
  pull: if-not-exists
  image: registry.bryk.io/general/golang:1.14
  commands:
  - echo "$DEPLOYMENT_KEY" | base64 -d > /drone/src/key
  - chmod 400 /drone/src/key
  environment:
    DEPLOYMENT_KEY:
      from_secret: deployment-key

- name: Verify style and consistency
  pull: if-not-exists
  image: registry.bryk.io/general/golang:1.14
  commands:
  - make lint

- name: Run unit tests
  pull: if-not-exists
  image: registry.bryk.io/general/golang:1.14
  commands:
  - make test

- name: Build project artifacts
  pull: if-not-exists
  image: registry.bryk.io/general/golang:1.14
  commands:
  - make build-for os=linux arch=amd64
  when:
    ref:
    - refs/tags/v*

- name: Report result
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack-webhook
    template: >
      {{#success build.status}}
        Build #{{build.number}} on repository {{repo.owner}}/{{repo.name}} succeeded.
        Author: {{build.author}}
        Branch: {{build.branch}}
        Build log is <{{build.link}}|available here>, commit <https://drone.bryk.io/link/{{repo.owner}}/{{repo.name}}/tree/refs/heads/{{build.branch}}?sha={{build.commit}}|source code> for more details.
      {{else}}
        Build #{{build.number}} on repository {{repo.owner}}/{{repo.name}} failed.
        Author: {{build.author}}
        Branch: {{build.branch}}
        Build log is <{{build.link}}|available here>, commit <https://drone.bryk.io/link/{{repo.owner}}/{{repo.name}}/tree/refs/heads/{{build.branch}}?sha={{build.commit}}|source code> for more details.
      {{/success}}

trigger:
  event:
  - push
  - tag

---
kind: signature
hmac: 7ec4a752eb7fe574e7a9816f1bfe1314c30d3763c4aea9f5fd8228d70e5e54e2

...
