[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/bryk-io/x"
  revision = "e921e2ebd60460fcf3bb784af20b0a9909a479d0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.0.0"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "github.com/cheggaaa/pb"
  version = "v1.0.25"
